export const topics = [
    "Your first day at school",
    "The most memorable trip you've taken",
    "Your favorite book",
    "Your favorite movie",
    "A hobby you are passionate about",
    "A place you would like to visit",
    "Your dream job",
    "A memorable childhood event",
    "Your favorite food",
    "A skill you want to learn",
    "Your most prized possession",
    "An interesting historical figure",
    "Your favorite season",
    "A song that means a lot to you",
    "Your favorite childhood game",
    "A book that changed your life",
    "A memorable family gathering",
    "Your favorite type of exercise",
    "A language you would like to learn",
    "Your favorite fictional character",
    "A personal achievement you are proud of",
    "A cultural tradition you cherish",
    "Your favorite quote",
    "A famous person you would like to meet",
    "A life lesson you've learned",
    "Your favorite form of art (painting, music, etc.)",
    "A technology that has impacted your life",
    "A place you consider your sanctuary",
];
